name: Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: node-version
        run: |
          echo "::set-output name=version::$(cat .nvmrc)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version.outputs.version }}
      - name: Install modules
        run: npm ci --also=dev
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm run test
